-- Phase 7: Extend audit enums for backup, retention, and SLA-config operations.
ALTER TYPE "AuditAction" ADD VALUE 'SLA_CONFIG_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'BACKUP_STARTED';
ALTER TYPE "AuditAction" ADD VALUE 'BACKUP_COMPLETED';
ALTER TYPE "AuditAction" ADD VALUE 'BACKUP_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'BACKUP_VERIFIED';
ALTER TYPE "AuditAction" ADD VALUE 'RETENTION_PREVIEW';
ALTER TYPE "AuditAction" ADD VALUE 'RETENTION_EXECUTED';
ALTER TYPE "AuditAction" ADD VALUE 'ARCHIVE_MARKED';

ALTER TYPE "AuditResource" ADD VALUE 'BACKUP';
ALTER TYPE "AuditResource" ADD VALUE 'RETENTION';
